### ISSUE TITLE
Add Kotlin Example for Key Rotation and Hashicorp Vault

### ISSUE THREAD

**Issue by 1123** [pneff93/csfle#11]
Nice Repository. Could we add an example for DEK rotation? Or extend the existing Kotlin example with Hashicorp to support key rotation?

We tried to add key rotation via the following configuration (notice the property `encrypt.dek.expiry.days`): 

```
curl --request POST --url "${SR_REST_ENDPOINT}/subjects/${TOPIC}-value/versions" \
  --user "${SR_API_KEY}:${SR_API_SECRET}" \
  --header 'Content-Type: application/vnd.schemaregistry.v1+json' \
  --data '{
        "ruleSet": {
        "domainRules": [
      {
        "name": "encryptPII",
        "kind": "TRANSFORM",
        "type": "ENCRYPT",
        "mode": "WRITEREAD",
        "tags": ["PII"],
        "params": {
           "encrypt.kek.name": "csfle",
           "encrypt.kms.key.id": "http://127.0.0.1:8200/transit/keys/csfle",
           "encrypt.kms.type": "hcvault",
           "encrypt.dek.expiry.days": 1
          },
        "onFailure": "ERROR,NONE"
        }
        ]
      }
   }'
```

Also we upgraded to version 7.5.0 of the library. This rsults in the following exceptions: 

10:37:03.572 [Thread-0] ERROR KafkaProducer - org.apache.kafka.common.errors.SerializationException: Rule failed: encryptPII for {"id": "0", "name": "Anna", "birthday": "1993-08-01", "timestamp": "2024-03-19T10:37:00.457Z"}
10:37:05.715 [Thread-0] ERROR KafkaProducer - org.apache.kafka.common.errors.SerializationException: Rule failed: encryptPII for {"id": "1", "name": "Joe", "birthday": "1996-09-11", "timestamp": "2024-03-19T10:37:05.577Z"}

**Comment by pneff93** [comment]
Solved by: https://github.com/pneff93/csfle/pull/12
